# Generated by Django 4.2.26 on 2025-11-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_hasownerpolymorphic_fileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderInfo',
            fields=[
                ('hasownerpolymorphic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.hasownerpolymorphic')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.CharField(choices=[('root_folder', 'Root Folder'), ('folder', 'Folder')], max_length=12)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.hasownerpolymorphic',),
        ),
    ]
